version: '3'
services:
  server:
    build: .
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - ./data.sqlite:/app/data.sqlite

  spell:
    build: ./hanspell-server
    restart: always